name: Atualizar Progresso

on:
  push:
    paths:
      - "modulos/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Calcular progresso
        id: calc
        run: |
          total=$(ls modulos | wc -l)
          feitos=$(grep -il "feito" modulos/* | wc -l)

          echo "{ \"done\": $feitos, \"total\": $total }" > .progress.json
          echo "done=$feitos" >> $GITHUB_OUTPUT
          echo "total=$total" >> $GITHUB_OUTPUT

      - name: Commit progresso atualizado
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Atualizando progresso automático"
          file_pattern: .progress.json
